#!/bin/bash

while [ true ]; do receive-file.py /run/shm/foo-image-nc; cp /run/shm/foo-image-nc /run/shm/foo-image; /home/pi/flipdots/scripts/display /run/shm/foo-image; rm /run/shm/foo-image-nc; done
